// Objeto que contiene curiosidades para cada palabra del juego
const curiosidades: Record<string, string> = {
    "COLLA": "La palabra 'COLLA' se refiere a un grupo de personas que comparten un mismo oficio o profesión, especialmente en el ámbito marítimo.",
    "MANGO": "El mango es una fruta tropical originaria del sur de Asia y es considerada por muchos como la 'reina de las frutas'.",
    "TENER": "El verbo 'tener' es uno de los más utilizados en español y cuenta con más de 50 acepciones en el diccionario de la RAE.",
    "SUAVE": "La palabra 'suave' proviene del latín 'suavis', que significa 'agradable' o 'dulce'.",
    "LLAVE": "Además de ser un instrumento para abrir cerraduras, 'llave' también es el nombre de una constelación.",
    "GRITO": "El grito más fuerte registrado por un ser humano alcanzó los 129 decibelios, similar al ruido de un avión despegando.",
    "CAMPO": "La palabra 'campo' deriva del latín 'campus', que originalmente significaba 'llanura' o 'espacio abierto'.",
    "LUCIR": "El verbo 'lucir' comparte origen etimológico con 'luz', ambos provienen del latín 'lucere' (brillar).",
    "PLANO": "En geometría, un plano es una superficie que contiene infinitos puntos y líneas rectas.",
    "NUBES": "Las nubes pueden pesar toneladas. Una nube cumulus mediana puede contener hasta 500 toneladas de agua.",
    "COSTA": "España tiene más de 8.000 kilómetros de costa, una de las más extensas de Europa.",
    "BOLSA": "La bolsa de valores más antigua del mundo que sigue operando es la de Ámsterdam, fundada en 1602.",
    "CIELO": "La palabra 'cielo' proviene del latín 'caelum', que también dio origen a palabras como 'celeste'.",
    "RUEDA": "La rueda fue inventada alrededor del año 3500 a.C. en Mesopotamia, revolucionando el transporte y la tecnología.",
    "BANDA": "En música, una banda sinfónica completa puede tener más de 100 músicos tocando simultáneamente.",
    "MAREA": "Las mareas son causadas principalmente por la atracción gravitacional de la Luna, y en menor medida por el Sol.",
    "JUEGO": "El juego más antiguo conocido es el 'Senet', practicado en el antiguo Egipto hace más de 5.000 años.",
    "RAMAS": "El árbol con más ramas del mundo es el baniano, que puede extenderse hasta cubrir varios acres de terreno.",
    "SALIR": "El verbo 'salir' proviene del latín 'salire', que significa 'saltar'.",
    "DULCE": "El ser humano puede distinguir hasta 20 sabores dulces diferentes gracias a receptores específicos en la lengua.",
    "BARRO": "El barro ha sido utilizado como material de construcción desde hace más de 10.000 años.",
    "TAZAS": "La taza de té más cara del mundo está hecha de oro y diamantes, y vale más de 3 millones de dólares.",
    "COPAS": "La copa más grande del mundo puede contener más de 1.000 litros de líquido y se encuentra en Portugal.",
    "CRUDO": "El término 'crudo' aplicado al petróleo viene de su estado natural sin refinar.",
    "LUNAR": "Un año lunar (12 ciclos completos de la Luna) dura aproximadamente 354 días.",
    "PEINE": "El peine más antiguo encontrado tiene más de 5.000 años y fue fabricado con hueso.",
    "GATOS": "Los gatos pueden hacer más de 100 sonidos vocales diferentes, mientras que los perros solo unos 10.",
    "JAULA": "La jaula más grande del mundo es una inmensa pajarera en Malasia que ocupa casi 21 hectáreas.",
    "TAPAR": "El verbo 'tapar' deriva de 'tapa', que proviene del gótico 'tappo', que significa 'tapón'.",
    "SABER": "La palabra 'saber' comparte raíz con 'sabiduría' y proviene del latín 'sapere', que significaba 'tener gusto'.",
    "HONGO": "Existe un hongo en Oregón que es considerado el organismo vivo más grande del planeta, ocupando casi 10 km².",
    "VELAS": "La vela más grande del mundo mide más de 36 metros de altura y se encuentra en Dubai.",
    "RATON": "Un ratón late unas 500 veces por minuto, lo que hace que su corazón sea uno de los más rápidos del reino animal.",
    "NORTE": "La palabra 'norte' proviene del antiguo inglés 'norð', relacionado con las lenguas nórdicas.",
    "CANTO": "El canto de algunas ballenas puede viajar más de 3.000 kilómetros bajo el agua.",
    "SOLAR": "Cada segundo, el Sol convierte 600 millones de toneladas de hidrógeno en helio mediante fusión nuclear.",
    "RIEGO": "Los sistemas de riego más antiguos conocidos datan del 6000 a.C. en Mesopotamia y Egipto.",
    "CURVA": "La curva matemática más larga tiene nombre infinito y su ecuación ocupa varias páginas.",
    "TIBIO": "La temperatura corporal normal está entre 36,5°C y 37,5°C, lo que se considera 'tibio'.",
    "PULSO": "El pulso normal de un adulto en reposo es de 60 a 100 latidos por minuto.",
    "MENTA": "La menta es una de las hierbas medicinales más antiguas y se ha encontrado en tumbas egipcias del 1000 a.C.",
    "LOCHA": "'Locha' es un regionalismo que en algunos países se refiere a una moneda de poco valor o a un pez de agua dulce.",
    "VISTA": "El ojo humano puede distinguir aproximadamente 10 millones de colores diferentes.",
    "SACAR": "El verbo 'sacar' es de origen desconocido y es una de las pocas palabras del español que no proviene del latín.",
    "RODEO": "El rodeo más antiguo del mundo se celebra en Payson, Arizona, desde 1884.",
    "HORNO": "El horno más caliente creado por el ser humano alcanzó 4 billones de grados Celsius, más caliente que el interior del Sol.",
    "FUEGO": "El fuego no tiene sombra porque es una fuente de luz, no un objeto físico que la bloquee.",
    "ALMAS": "La creencia en el alma existe en casi todas las culturas del mundo desde la prehistoria.",
    "SUELO": "Un puñado de suelo fértil contiene más microorganismos que personas hay en la Tierra.",
    "LIGAR": "El verbo 'ligar' proviene del latín 'ligare', que significa 'atar' o 'unir'."
};

export default curiosidades;