const curiosidades: Record<string, string> = {
    "COLLA": "En Cataluña, una 'colla' es un grupo de personas que forman torres humanas llamadas castells.",
    "MANGO": "El mango es conocido como el 'rey de las frutas' en la India y tiene más de 500 variedades.",
    "TENER": "El verbo 'tener' es uno de los más usados en español y proviene del latín 'tenere'.",
    "SUAVE": "La palabra 'suave' viene del latín 'suavis' que significa 'dulce' o 'agradable'.",
    "LLAVE": "Las primeras llaves metálicas fueron usadas por los romanos en el siglo I.",
    "GRITO": "Un grito humano puede alcanzar hasta 129 decibelios, similar a un concierto de rock.",
    "CAMPO": "El 38% de la superficie terrestre se dedica a la agricultura, es decir, campo cultivable.",
    "LUCIR": "En astronomía, una estrella que 'luce' mucho puede ser una supergigante a punto de explotar.",
    "PLANO": "Los planos arquitectónicos más antiguos conocidos son de 2200 a.C. en Mesopotamia.",
    "NUBES": "Las nubes pueden pesar más de 500 toneladas, pero flotan porque su densidad es menor que el aire.",
    "COSTA": "España tiene más de 8.000 km de costa, lo que influye en su clima y turismo.",
    "BOLSA": "La primera bolsa de valores del mundo se fundó en Amberes en 1460.",
    "CIELO": "El cielo es azul debido a un fenómeno llamado dispersión de Rayleigh.",
    "RUEDA": "La rueda se inventó alrededor del 3.500 a.C. en Mesopotamia.",
    "BANDA": "Las primeras bandas musicales militares surgieron en el antiguo Egipto.",
    "MAREA": "Las mareas son más altas durante la luna llena y nueva debido a la alineación Sol-Luna-Tierra.",
    "JUEGO": "Los juegos de mesa más antiguos tienen más de 5.000 años de antigüedad.",
    "RAMAS": "Las ramas de los árboles pueden comunicarse entre sí mediante señales químicas.",
    "SALIR": "El verbo 'salir' viene del latín 'salire' que significa 'saltar'.",
    "DULCE": "El azúcar fue tan valioso en la Edad Media que se le llamaba 'oro blanco'.",
    "BARRO": "El barro ha sido usado para construir casas durante más de 10.000 años.",
    "TAZAS": "La primera taza de té fue creada en China durante la dinastía Han (206 a.C. - 220 d.C.).",
    "COPAS": "Las copas de cristal se inventaron en Venecia en el siglo XV.",
    "CRUDO": "El sushi originalmente era pescado crudo fermentado durante meses.",
    "LUNAR": "Los lunares son pequeñas áreas de piel con alta concentración de melanina.",
    "PEINE": "El peine más antiguo conocido tiene 8.000 años y fue hecho de hueso.",
    "GATOS": "Los gatos pueden hacer más de 100 sonidos vocales diferentes.",
    "JAULA": "Las jaulas doradas para pájaros eran símbolos de estatus en la antigua China.",
    "TAPAR": "Los primeros tapones de corcho se usaron en ánforas romanas hace 2.000 años.",
    "SABER": "La palabra 'saber' viene del latín 'sapere' que significa 'tener gusto'.",
    "HONGO": "Existe un hongo que puede sobrevivir en el espacio exterior.",
    "VELAS": "Las primeras velas se hicieron de grasa animal hace más de 5.000 años.",
    "RATON": "Los ratones pueden cantar a frecuencias ultrasónicas para atraer pareja.",
    "NORTE": "La estrella Polar no siempre ha sido la estrella del Norte debido a la precesión terrestre.",
    "CANTO": "Algunas aves pueden aprender nuevas canciones durante toda su vida.",
    "SOLAR": "La energía solar que llega a la Tierra en una hora podría abastecer al mundo durante un año.",
    "RIEGO": "El riego por goteo fue inventado en Israel para ahorrar agua en el desierto.",
    "CURVA": "La curva más perfecta en matemáticas es la espiral logarítmica.",
    "TIBIO": "El agua tibia se congela más rápido que el agua fría (Efecto Mpemba).",
    "PULSO": "El pulso normal de un colibrí puede alcanzar los 1.260 latidos por minuto.",
    "MENTA": "La menta puede reducir la temperatura percibida en 8 grados centígrados.",
    "LOCHA": "La locha es un pez que puede respirar aire y sobrevivir fuera del agua.",
    "VISTA": "El ojo humano puede distinguir aproximadamente 10 millones de colores.",
    "SACAR": "La palabra 'sacar' originalmente significaba 'extraer agua de un pozo'.",
    "RODEO": "El primer rodeo documentado se realizó en México en el siglo XVI.",
    "HORNO": "El horno más antiguo conocido tiene 6.500 años y fue encontrado en Croacia.",
    "FUEGO": "Los humanos son los únicos seres vivos que pueden crear y controlar el fuego.",
    "ALMAS": "La creencia en el alma existe en casi todas las culturas conocidas.",
    "SUELO": "Un centímetro de suelo fértil puede tardar más de 1.000 años en formarse.",
    "LIGAR": "La palabra 'ligar' viene del latín 'ligare' que significa 'atar' o 'unir'."
};

export default curiosidades;